name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  objectbox: ^5.0.2
  tflite_flutter: ^0.12.1
  llama_cpp_dart: ^0.1.2+1
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  ffi: ^2.1.4
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3

flutter:

  uses-material-design: true
